apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      wal:
        enabled: true
        dir: /loki/wal
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 15m
      max_transfer_retries: 0
      chunk_retain_period: 30s
      max_chunk_age: 1h
      chunk_target_size: 1048576
      chunk_block_size: 262144
    schema_config:
      configs:
        - from: 2022-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/boltdb-shipper-active
        cache_location: /tmp/loki/boltdb-cache
        cache_ttl: 24h
        shared_store: filesystem
    limits_config:
      retention_period: 24h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 24h
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: filesystem
      working_directory: /tmp/loki/compactor
      retention_delete_delay: 1h
      retention_enabled: true