kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-loki
  namespace: logging
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-loki
  resources:
    requests:
      storage: 10Gi
