apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: grafana--preproduction
  namespace: grafana
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: grafana--preproduction
  namespace: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana--preproduction
  namespace: grafana
automountServiceAccountToken: true