kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-grafana
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-grafana
  resources:
    requests:
      storage: 1Gi