apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx:1.14.3
spec:
  selector:
    matchLabels:
      app: nginx:1.14.3
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx:1.14.3
    spec:
      containers:
      - name: nginx:1.14.3
        image: nginx:1.14.3
        ports:git 
        - containerPort: 80
---