apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-ci-cd--uat
spec:
  selector:
    matchLabels:
      app: echo-ci-cd--uat
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-ci-cd--uat
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
      - name: echo-ci-cd--uat
        image: efishery.azurecr.io/echo-ci-cd--uat:6
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: echo-configmap
                key: db_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: echo-configmap
                key: db_port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: echo-configmap
                key: db_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: echo-secret
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: echo-secret
                key: db_password
        ports:
        - containerPort: 8080