apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-ci-cd
  name: echo-ci-cd
  namespace: default
spec:
  selector:
    app: echo-ci-cd
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-1
  namespace: default
automountServiceAccountToken: true