apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: redis--staging
  namespace: staging
spec:
  protocol: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: redis--staging
  namespace: staging
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: tcp-redis
  selector:
    app: redis--staging
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis--staging
  namespace: staging
automountServiceAccountToken: true