kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-redis
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-redis
  resources:
    requests:
      storage: 1Gi