apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-app
  labels:
    app: logging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-app
  template:
    metadata:
      labels:
        app: logging-app
    spec:
      containers:
        - name: logging-app-container
          image: gcr.io/google_containers/busybox
          args:
          - /bin/sh
          - -c
          -  while :; do echo "level=info this is a log message from loggy McLogface at $(date)"; sleep 5; done