apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-ci-cd--staging
spec:
  selector:
    matchLabels:
      app: echo-ci-cd--staging
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-ci-cd--staging
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-webapp: 'secret/data/webapp/config'
        vault.hashicorp.com/agent-inject-template-webapp: |
          {{- with secret "secret/data/webapp/config" -}}
          {{- range $k, $v := .Data.data -}}
          {{ $k }}: {{ $v }}
          {{ end }}
          {{- end -}}
        vault.hashicorp.com/secret-volume-path-webapp: '/app/.env'
        vault.hashicorp.com/agent-inject-file-webapp: '.env'
        vault.hashicorp.com/role: 'echo-ci-cd--staging'
    spec:
      containers:
      - name: echo-ci-cd--staging
        image: efishery.azurecr.io/echo-ci-cd--staging:14
        env:
          - name: VAULT_ADDR
            value: 'http://vault.vault:8200'
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: echo-configmap
                key: db_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: echo-configmap
                key: db_port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: echo-configmap
                key: db_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: echo-secret
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: echo-secret
                key: db_password
        ports:
        - containerPort: 8080