apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: emqx--staging
  namespace: staging
spec:
  protocol: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: emqx--staging
  namespace: staging
spec:
  ports:
    - name: amqp-emqx
      port: 1883
      protocol: TCP
      targetPort: mqtt-emqx
    - name: gui-emqx
      port: 18083
      protocol: TCP
      targetPort: gui-emqx
  selector:
    app: emqx--staging
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx--staging
  namespace: staging
automountServiceAccountToken: true